pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Подтягиваем код из репозитория
                checkout scm
            }
        }

        stage('Build Service A') {
            steps {
                dir('lab2/service-a') {
                    script {
                        // Собираем образ для первого сервиса
                        sh "docker build -t service-a:${env.BUILD_ID} ."
                    }
                }
            }
        }

        stage('Build Service B') {
            steps {
                dir('lab2/service-b') {
                    script {
                        // Собираем образ для второго сервиса
                        sh "docker build -t service-b:${env.BUILD_ID} ."
                    }
                }
            }
        }

        stage('Test Run (Compose)') {
            steps {
                dir('lab2') {
                    // Проверяем, что всё вместе поднимается
                    sh "docker-compose up -d"
                    sh "docker-compose ps"
                    sh "docker-compose down"
                }
            }
        }
    }
}
